import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import { projects, siteData, techStack } from '../data'
import ProjectCard from './ProjectCard'

export function ProjectsPage() { return <PageFrame label="02 / all projects" title="Everything I have shipped"><p className="max-w-xl leading-8 text-[#888]">The complete public archive: interfaces, business tools, dashboards, and Android experiments.</p><div className="mt-14 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{projects.map((project, index) => <ProjectCard key={project.title} project={project} index={index} />)}</div></PageFrame> }

export function AboutPage() { return <PageFrame label="04 / whoami" title="About Rio"><div className="grid gap-12 lg:grid-cols-[1fr_1.3fr]"><div className="text-2xl leading-10 text-[#ddd]">A software engineering student from West Jakarta who likes taking an idea from a rough sketch to a working deploy.</div><div className="space-y-6 leading-8 text-[#888]"><p>I started with frontend interfaces and kept moving deeper into the stack: data models, APIs, authentication, operations, and deployment. Each project is a chance to understand a real problem better.</p><p>Outside the code, I am currently exploring AI, automation, and the craft of making digital products feel clear and useful.</p><div className="grid gap-6 border-t border-white/10 pt-6 font-mono text-sm sm:grid-cols-2">{[['name', siteData.name], ['based in', siteData.location], ['status', 'open to work'], ['focus', 'web + Android']].map(([key, value]) => <p key={key}><span className="text-[#555]">→ {key}</span><br /><span className="text-white">{value}</span></p>)}</div></div></div><div className="mt-20 border-t border-white/10 pt-12"><h2 className="text-4xl font-medium text-white">The toolkit</h2><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{techStack.map((tech) => <span data-spotlight key={tech.name} className="flex items-center gap-3 border border-white/10 px-4 py-3 font-mono text-xs text-[#888]"><img src={tech.icon} alt="" className="h-5 w-5" />{tech.name}</span>)}</div></div></PageFrame> }

export function ProjectDetailPage({ slug }: { slug: string }) { const project = projects.find((item) => item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') === slug) ?? projects[0]; return <PageFrame label={`project / ${String(projects.indexOf(project) + 1).padStart(2, '0')}`} title={project.title}><div className="grid gap-12 lg:grid-cols-[1fr_1.2fr]"><div><p className="font-mono text-sm text-[#00ff88]">{project.tags.join(' · ')}</p><p className="mt-8 text-xl leading-9 text-[#ccc]">{project.description}</p><a data-cursor href={project.github} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 border border-[#00ff88] px-5 py-3 font-mono text-xs uppercase text-[#00ff88]">View on GitHub <ArrowUpRight size={14} /></a></div><div className="terminal-panel p-6 font-mono text-sm text-[#888]"><p className="text-[#555]">// project notes</p><p className="mt-6"><span className="text-[#00ff88]">title</span> = &quot;{project.title}&quot;</p><p><span className="text-[#00ff88]">stack</span> = [{project.tags.map((tag) => `&quot;${tag}&quot;`).join(', ')}]</p><p><span className="text-[#00ff88]">source</span> = &quot;public GitHub repository&quot;</p></div></div><a href="/projects" className="mt-20 inline-flex items-center gap-2 font-mono text-xs uppercase text-[#888] hover:text-[#00ff88]"><ArrowLeft size={14} /> all projects</a></PageFrame> }

function PageFrame({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <main className="relative z-[1] mx-auto min-h-[100dvh] max-w-6xl px-6 pb-24 pt-36"><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#00ff88]">{label}</p><h1 className="mt-5 max-w-4xl text-6xl font-medium leading-none tracking-[-0.07em] text-white sm:text-8xl">{title}</h1><div className="mt-12">{children}</div></main> }
